server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
product:
  service:
    url: http://localhost:9000/api/v1/